### ISSUE TITLE
Environment key "jest/globals" is unknown

### ISSUE THREAD

**Issue by minblake** [nuxt/eslint-config#98]
I'm getting this error on a fresh install of `create-nuxt-app` with linting tools of eslint and prettier enabled

```
> eslint --ext .js,.vue --ignore-path .gitignore . "--fix"

Error: .eslintrc.js » @nuxtjs/eslint-config-typescript » @nuxtjs/eslint-config:
        Environment key "jest/globals" is unknown

    at /home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/shared/config-validator.js:169:19
    at Array.forEach (<anonymous>)
    at validateEnvironment (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/shared/config-validator.js:163:30)
    at validateConfigArray (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/shared/config-validator.js:334:9)
    at CascadingConfigArrayFactory._finalizeConfigArray (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:417:13)
    at CascadingConfigArrayFactory.getConfigArrayForFile (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/cli-engine/cascading-config-array-factory.js:271:21)
    at FileEnumerator._iterateFilesRecursive (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/cli-engine/file-enumerator.js:396:49)
    at _iterateFilesRecursive.next (<anonymous>)
    at FileEnumerator.iterateFiles (/home/kdjs8967/nuxtjs-test/node_modules/eslint/lib/cli-engine/file-enumerator.js:251:49)
    at iterateFiles.next (<anonymous>)
```

The `.eslintrc.js` is the default one

```
module.exports = {
  root: true,
  env: {
    browser: true,
    node: true
  },
  extends: [
    '@nuxtjs/eslint-config-typescript',
    'prettier',
    'prettier/vue',
    'plugin:prettier/recommended',
    'plugin:nuxt/recommended'
  ],
  plugins: [
    'prettier'
  ],
  // add your custom rules here
  rules: {
  }
}
```

**Comment by buecki** [comment]
Everything worked fine yesterday, now I have exactly the same problem and haven't found a solution yet.

**Comment by buecki** [comment]
@minblake I just tried again and it suddenly works for me although I haven't changed anything :-)

**Comment by minblake** [comment]
@buecki Yeah, same thing happend to me. Strange.. Anyways, thank you!

**Comment by edwin177** [comment]
Just ran into this issue using:

```
"@nuxtjs/eslint-config-typescript": "1.0.2",
"eslint": "6.8.0",
```

Did you do anything to fix it?

**Comment by minblake** [comment]
@edwin177 the error just suddenly disappeared, so sadly, no. Maybe try deleting your `node_modules` and installing it again but I can't guarantee you it will work

**Comment by edwin177** [comment]
Couldn't figure out, but upgrading eslint worked for me:

```
"@nuxtjs/eslint-config-typescript": "2.0.0",
"eslint": "7.0.0",
```

**Comment by lephuongbg** [comment]
Version 3 of "@nuxtjs/eslint-config-typescript" doesn't work at the moment. Same error.
```
"@nuxtjs/eslint-config-typescript": "^3.0.0",
"eslint": "^7.5.0",
"eslint-plugin-import": "^2.22.0", // <- Not sure why I suddenly need to install this with version 3?
```

**Comment by Sletheren** [comment]
+1

**Comment by SixBytesUnder** [comment]
I run into this today. Already deleted `package-lock` and `node-modules` and reinstalled everything, didn't help :(
```
  "devDependencies": {
    "@nuxtjs/eslint-config": "^6.0.1",
    "@nuxtjs/eslint-module": "^3.0.2",
    "babel-core": "7.0.0-bridge.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^8.0.1",
    "eslint-plugin-nuxt": "^2.0.0"
  }
```

**Comment by aparajita** [comment]
Is there any special reason you are depending on `eslint-plugin-jest`? I know it may seem hard to believe, but some of us neither use jest nor want to install it. Making jest a hard-coded dependency to lint Nuxt code seems a bit opinionated.
